# Generated by Django 4.1.3 on 2022-12-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
