# Generated by Django 4.1.3 on 2022-12-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='thumb')),
            ],
        ),
    ]
